#!/bin/bash

set -exuo pipefail

. config

wpa_country=${WPA_COUNTRY}
wpa_ssid=${WPA_SSID}
# WPA_PSK should be the hash generated using `wpa_passphrase $WPA_SSID`
wpa_psk=${WPA_PSK}
provisioner_url=${PROVISIONER_URL}
provisioner_port=${PROVISIONER_PORT}
provisioner_pubkey=${PROVISIONER_PUBKEY}
# authorization_token=${AUTHORIZATION_TOKEN}

# Must be passed as an argument; make sure it is the correct device
# that the SD card you want to write the image to is shown as!
# Example invokation with the SD card shown by `lsblk` as `/dev/sda`: `./rpi-bootstrap /dev/sda`
sd_card=${1:-}

rpi_release=$(basename -s .zip ${RPI_RELEASE_URL})
rpi_release_url=${RPI_RELEASE_URL}
checksum=${RPI_RELEASE_CHECKSUM}
curdir=$(pwd)
tmpdir=${TMP_DIR:- "/tmp"}
workdir="${curdir}/work"
mkdir -p ${workdir}
image="${workdir}/${rpi_release}.img"
archive="${workdir}/${rpi_release}.zip"

if ! [ -f "${image}" ]; then
    echo "No raspbian image found, fetching..."
    if ! [ -f "${archive}" ]; then
        echo "No raspbian image archive found, downloading ${rpi_release}..."
        pushd ${workdir}
        curl -LO ${rpi_release_url}
        popd
        archive_checksum="$(cat ${archive} | sha256sum | awk -F ' ' '{print $1}')"
        if ! [ "${checksum}" = "${archive_checksum}" ]; then
            echo "bad checksum - try again or update \$hash for newer release"
            rm ${archive}
            exit 1
        fi
    else
        echo "Raspbian image archive found, skipping download and extracting..."
    fi
    unzip ${archive} -d ${workdir}/
fi

[ -f "${image}" ]

tmpworkdir="${tmpdir}/rpi-bootstrap-work"
sudo mkdir -p ${tmpworkdir}
tmpimage="${tmpworkdir}/${rpi_release}.img"
sudo cp ${image} ${tmpimage}

[ -f "${tmpimage}" ]

# TODO: add files via generic filesystem config.
rpi_wpa_supplicant=$(cat <<EOF
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=${wpa_country}
network={
    ssid="${wpa_ssid}"
    psk=${wpa_psk}
}
EOF
    )
rpi_provision_checkin=$(cat <<EOF
[Unit]
Description=Check in to a rpi-provision server to request provisioning. Once provisioning is complete, this unit should be stopped and disabled by the server.
Before=systemd-user-sessions.service
Wants=network-online.target
After=network-online.target

[Service]
Restart=on-failure
RestartSec=10s
RemainAfterExit=yes
ExecStart=/usr/bin/curl --request POST --header "Content-Type: application/json" --data "{ \"ssh_port\": 22, \"ssh_user\": \"pi\" }" --url http://${provisioner_url}:${provisioner_port}/v0/checkin/

[Install]
WantedBy=multi-user.target
EOF
    )

# workaround when VirtualBox is running, see https://bugzilla.redhat.com/show_bug.cgi?id=1277744
LIBGUESTFS_BACKEND_SETTINGS=
if pgrep -f '/virtualbox/V.*--startvm\>'; then
    LIBGUESTFS_BACKEND_SETTINGS='force_tcg'
fi

sudo LIBGUESTFS_BACKEND_SETTINGS=${LIBGUESTFS_BACKEND_SETTINGS} guestfish --rw -i -a ${tmpimage} <<EOF
list-filesystems
ln-s /lib/systemd/system/ssh.service /etc/systemd/system/sshd.service
ln-s /lib/systemd/system/ssh.service /etc/systemd/system/multi-user.target.wants/ssh.service
upload -<<GF_EOF /etc/wpa_supplicant/wpa_supplicant.conf
${rpi_wpa_supplicant}
GF_EOF
upload -<<GF_EOF /lib/systemd/system/rpi-provision-checkin.service
${rpi_provision_checkin}
GF_EOF
ln-s /lib/systemd/system/rpi-provision-checkin.service /etc/systemd/system/multi-user.target.wants/rpi-provision-checkin.service
mkdir-p /home/pi/.ssh
write-append /home/pi/.ssh/authorized_keys "${provisioner_pubkey}"
EOF

out_image="${workdir}/${rpi_release}.out.img"
sudo mv -f ${tmpimage} ${out_image}
sudo chown $USER:$USER ${out_image}
sudo rmdir ${tmpworkdir}

# TODO: split this into a separate stage
if [ "${sd_card}" ]; then
    sudo dd if=${out_image} of=${sd_card} bs=4M oflag=dsync status=progress
    sync
else
    echo Image is not written
fi
